name: roleplay-ai
volumes:
  hugging_face: {}
services:
  app:
    build:
      dockerfile: training/Dockerfile
      no_cache: true
    env_file:
      - .env
    restart: no
    volumes:
      - hugging_face:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities:
                - gpu
