name: roleplay-ai
volumes:
  mariadb_data: {}
  ollama: {}
  qdrant_storage: {}
  mongodata_db: {}
  mongodata_config: {}
  redis: {}
  grafana_storage: {}
  prometheus_storage: {}
services:
  grafana:
    build:
      dockerfile: Grafana/Dockerfile
      no_cache: true
    restart: always
    ports:
      - '127.0.0.1:8012:3000'
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.bjoern-buettner.me/"
    healthcheck:
      test: [ "CMD", "echo", "0" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - grafana_storage:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      mariadb:
        condition: service_healthy
  prometheus:
    image: prom/prometheus:v2.53.5
    healthcheck:
      test: [ "CMD", "echo", "0" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - prometheus_storage:/prometheus
  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
  ollama:
    image: ollama/ollama
    post_start:
      - command: "ollama cp mistral:instruct $LLM_MODEL_PLAY"
      - command: "ollama cp mistral:instruct $LLM_MODEL_SUMMARY"
      - command: "ollama run $LLM_MODEL_PLAY"
      - command: "ollama run $LLM_MODEL_SUMMARY"
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: 15
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      OLLAMA_MAX_LOADED: 2
      OLLAMA_KEEP_ALIVE: -1
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
  qdrant:
    image: qdrant/qdrant
    restart: always
    healthcheck:
      test: ["CMD", "echo", "0"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - qdrant_storage:/qdrant/storage
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "echo", "0"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "echo", "0"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodata_db:/data/db
      - mongodata_config:/data/configdb
  app:
    build:
      dockerfile: App/Dockerfile
      no_cache: true
    env_file:
      - .env
    restart: always
    ports:
      - '127.0.0.1:8000:80'
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      prometheus:
        condition: service_healthy
  ui:
    build:
      dockerfile: Ui/Dockerfile
      no_cache: true
    restart: always
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '127.0.0.1:8080:80'