server {
  listen 80;
  listen [::]:80;

  root /usr/share/nginx/html;

  location / {
    index index.html;
    try_files $uri /index.html;
  }

  location ~* \.(avif|webp|jpg|jpeg|png|svg|mp3)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Vary "Accept";
  }

  location ~* \.(min\.js|css)$ {
    expires 1m;
    add_header Cache-Control "public, immutable";
    add_header Vary "Accept";
  }

  location /chat {
    index index.html;
    try_files $uri /chat.html;
  }

  location /imprint {
    index index.html;
    try_files $uri /imprint.html;
  }

  location /login {
    index index.html;
    try_files $uri /login.html;
  }
}
