name: Game Master Deployment
on:
  push:
    branches:
      - the-one
    paths:
    - beam-llm-hosting-gamemaster/*.py
    - beam-llm-hosting-gamemaster/*.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Docker-Image
      run: docker buildx build --build-arg BEAM_TOKEN=${{secrets.BEAM_TOKEN}} --tag=todeploy ./beam-llm-hosting-gamemaster/Dockerfile && docker run todeploy
