name: Mark stale issues and pull requests
on:
  schedule:
  - cron: '26 12 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is considered stale now'
        stale-pr-message: 'This pr is considered stale now'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
