name: Fine Tune Story Summariser
on:
  push:
    branches:
      - the-one
    paths:
    - beam-llm-training/shared/*.py
    - beam-llm-training/storysummariser/*.py
    - beam-llm-training/storysummariser/data/*.yml
    - beam-llm-training/storysummariser/*.txt
    - beam-llm-training/storysummariser/Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Docker-Image
      run: docker buildx build --build-arg BEAM_TOKEN=${{secrets.BEAM_TOKEN}} --tag=totrain -f ./beam-llm-training/storysummariser/Dockerfile . && docker run totrain
