name: Fine Tune Character Builder
on:
  workflow_dispatch: {}
  push:
    branches:
      - the-one
    paths:
    - beam-llm-training/shared/*.py
    - beam-llm-training/characterbuilder/*.py
    - beam-llm-training/characterbuilder/data/*.yml
    - beam-llm-training/characterbuilder/*.txt
    - beam-llm-training/characterbuilder/Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run Docker-Image
      run: docker buildx build --build-arg BEAM_TOKEN=${{secrets.BEAM_TOKEN}} --tag=totrain -f ./beam-llm-training/characterbuilder/Dockerfile . && docker run totrain
